import Head from 'next/head'
import NavBar from '../assets/components/NavBar/NavBar'
import HeroHome from '../components/Home/HeroHome'

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>Personal Website with Next</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main >
          <NavBar />
          <HeroHome />
        </main>
      </div>
      <style jsx>
      {`
        main{
          with: 100vw;
          min-height: 100vh;
          background-color: white;
        }
      `}
      </style>
    </>
  )
}
