import Head from 'next/head'
import Footer from '../assets/components/Footer/Footer'
import ArticleCase from '../assets/components/Home/ArticlesCase'
import NavBar from '../assets/components/NavBar/NavBar'
import HeroHome from '../components/Home/HeroHome'

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>Personal Website with Next</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main >
          <NavBar />
          <HeroHome />
          <ArticleCase />
          <Footer />
        </main>
      </div>
      <style jsx>
      {`
        main{
          position: relative;
        }
      `}
      </style>
    </>
  )
}
